apiVersion: v1
kind: Service
metadata:
   name: node-mongo
   labels:
     run: node-mongo
spec:
   ports:
   - port: 80
     targetPort: 3000
     protocol: TCP
   type: LoadBalancer
   selector:
     run: node-mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-mongo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: node-mongo
    spec:
      containers:
      - name: node-mongo
        image: gcr.io/nebula-tasks/nebula-demo
        ports:
        - containerPort: 3000
---
